services:

  web:
    build:
      target: dev
    container_name: ${APP_NAME}_fastapi_${APP_ENVIRONMENT}
    volumes:
      - ./../../../code/${APP_NAME}:/code
    command: fastapi run app.py --port 8090
