networks:
 app_network:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge

services:

  web_app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: web_app.dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - NGINX_VERSION=${NGINX_VERSION}
        - APP_DOMAIN=${APP_DOMAIN}
        - PATH_TO_CODE=${PATH_TO_CODE}
        - CODE_REPO_URL=${CODE_REPO_URL}
    image: ${REGISTRY_URL}/${REGISTRY_REPO}:${REGISTRY_DEPLOYED_VERSION}
    ports:
      - ${HTTP_ON_HOST}:80
      - ${HTTPS_ON_HOST}:443
    networks:
      - app_network
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
