services:

  mysql:
    image: arm64v8/mysql:${MYSQL_VERSION}
    container_name: ${APP_NAME}_mysql_${APP_ENVIRONMENT}
    ports:
      - ${MYSQL_ON_HOST}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

