services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [ node.role == manager ]