services:

  web:
    platform: linux/amd64
    build:
      target: prod
    container_name: ${APP_NAME}_django_${APP_ENVIRONMENT}
    volumes:
      - ./../../../code/${APP_NAME}:/app
    command: /entry_point.sh
