version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: web.dockerfile
      target: prod
      args:
        - NGINX_VERSION=${NGINX_VERSION}
        - APP_DOMAIN=${APP_DOMAIN}
        - CODE_REPO_URL=${CODE_REPO_URL}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASSWORD}
    ports:
      - "${HTTP_ON_HOST}:80"
      - "${HTTPS_ON_HOST}:443"

